### ISSUE TITLE
"ImportError: cannot import name tests"

### ISSUE THREAD

**Issue by rodricios** [kragniz/json-sempai#10]
I am a masochist. I cannot stop until I unleash this wretched beast and let it wreak havoc upon my world. 

But for serious now, any idea why "pip install json-sempai" won't also download the "tests" directory? fyi, I'm on a windows machine.

**Comment by borntyping** [comment]
The `setup.py` package does not include the `jsonsempai.tests` package - https://github.com/kragniz/json-sempai/blob/master/setup.py#L30

**Comment by rodricios** [comment]
Ah, was this intended?

**Comment by kragniz** [comment]
Thanks, this was not intended. 0.3.1 should have this fixed.

**Comment by rodricios** [comment]
Awesome, thanks!
